[tool.black]
    target-version            = ['py311']
    extend-exclude            = "^venv$"
    include                   = '(\.ipynb$|\.py$)'
    line-length               = 120
    skip-string-normalization = true

[tool.ruff]
    line-length = 120

[tool.ruff.format]
    quote-style = "preserve"
