# See: https://github.com/squillero/style/blob/master/python.md

[tool.yapf]
based_on_style = "google"
column_limit = 120
blank_line_before_module_docstring = true

[tool.black]
line-length = 120
include = '\.ipynb'
